Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Lint/RescueException:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'strict_money.gemspec'

# Handled by Reek
Metrics/MethodLength:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'spec/**/*'

Style/ExpandPathArguments:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RandomWithOffset:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/**/*'

Style/TrivialAccessors:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
